apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clouddevops-app
  namespace: argo
spec:
  project: default
  source:
    repoURL: https://github.com/TokaMohsenSaad/Cloud_Devops_Project.git
    targetRevision: HEAD
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: ivolve
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true