apiVersion: v1
kind: Service
metadata:
  name: ivolve-service
  namespace: ivolve
spec:
  selector:
    app: ivolve
  ports:
  - protocol: TCP
    targetPort: 5000
    port: 80
  type: ClusterIP

    